### ISSUE TITLE
parameter check in mutPolynomial doesn't check 'upper'

### ISSUE THREAD

**Issue by mb706** [jakobbossek/ecr2#101]
[This](https://github.com/jakobbossek/ecr2/blob/7a1f3c20b9a91861306549ea90e2191664482437/R/operator.mutator.polynomial.R#L24-L25) checks `lower` twice and `upper` not at all.

**Comment by jakobbossek** [comment]
Thanks for the report 👍

**Comment by jakobbossek** [comment]
Done 👍
