### ISSUE TITLE
isMaximallyDominated doesn't do what it says in the documentation

### ISSUE THREAD

**Issue by mb706** [jakobbossek/ecr2#102]
`isMaximallyDominated` returns a vector indicating the points in the last nondominated front, but these are not necessarily the only points that do not dominate any other point, for example in
```r
mat <- cbind(c(1,1),c(3,0),c(0,3),c(2,2))
isMaximallyDominated(mat)
## [1] FALSE FALSE FALSE  TRUE
# even though points 2 and 3 do not dominate any other point
```
(Sorry if I'm being nitpicky)

**Comment by jakobbossek** [comment]
Thanks for the report! 👍 
I fixed the documentation. Going to add another function which determines all points which do not dominate any other point.
