### ISSUE TITLE
Issue with rgl on travis

### ISSUE THREAD

**Issue by jakobbossek** [jakobbossek/ecr2#105]
We have a problem with package `rgl` on travis. Plotting device X11 cannot be initialized. See https://github.com/terrytangyuan/lfda/issues/5 for a discussion on this topic. Maybe we need to get rid of the rgl-dependency.

**Comment by jakobbossek** [comment]
@thllwg Could you please assist with the search for a fix?

**Comment by thllwg** [comment]
Cf pull #114, added RGL_USE_NULL to .travis.yml

**Comment by jakobbossek** [comment]
Fixed via 53adbfb 👏
