### ISSUE TITLE
evaluateFitness does not parallelize when fitness.fun is a smoof function

### ISSUE THREAD

**Issue by mb706** [jakobbossek/ecr2#107]
`evaluateFitness` [calls `parallelMap`](https://github.com/jakobbossek/ecr2/blob/8625fa2a0572d7ed5aef82af8d8e988e91deaf93/R/evaluateFitness.R#L36-L37) for ordinary fitness functions, but [does not do so](https://github.com/jakobbossek/ecr2/blob/8625fa2a0572d7ed5aef82af8d8e988e91deaf93/R/evaluateFitness.R#L29) for smoof functions that do not vectorize.

**Comment by jakobbossek** [comment]
Going to fix this. Thanks!
@thllwg Can you please fix this?
