### ISSUE TITLE
Segfault in computeHVContr with only one point

### ISSUE THREAD

**Issue by mb706** [jakobbossek/ecr2#109]
```r
> computeHVContr(matrix(c(1, 1), nrow = 2), c(2, 2))

 *** caught segfault ***
address 0x10, cause 'memory not mapped'
```

**Comment by jakobbossek** [comment]
Thanks for the report. Going to catch this case and return an error message. IMHO this calculation does not make sense for a single point.

**Comment by mb706** [comment]
Its not exactly useful when comparing points to decide which ones to drop, but I'd imagine the HV contribution of a single point with a reference point is just the HV of the hyperrectangle spanned by the two---1 in the example above?
