### ISSUE TITLE
mutPolynomial gives useless results

### ISSUE THREAD

**Issue by mb706** [jakobbossek/ecr2#113]
When I call `mutPolynomial` I get useless results:
```r
> mutPolynomial(c(1, 2, 3, 4, 5, 6, 7, 8), p = 1, eta = 25, lower = 0, upper = 9)
[1]  1.015549e+00           NaN           NaN 4.672394e-310 4.672394e-310
[6]           NaN           NaN  2.500000e+01
```
There is probably something being read from uninitialized memory. Can you reproduce this? It might be dependent on compiler flags or R version.

**Comment by jakobbossek** [comment]
Had a look at it. Arguments `lower` and `upper` need to be of length d, where d is the dimension of the input vector. This is currently not catched internally and hence the C-code quietly produces nonsense output. Thanks for the report!

By the way: are you actively looking for bugs? 😆

**Comment by mb706** [comment]
I'm working on a project that heavily depends on ecr2: https://compstat-lmu.github.io/mosmafs/ so I run into these things :wink:

**Comment by jakobbossek** [comment]
Nice! Give my best regards to Bernd.
The bug should be fixed now.
