### ISSUE TITLE
custom.constants ignored in ecr()

### ISSUE THREAD

**Issue by miguel-porto** [jakobbossek/ecr2#72]
Hi, just to note that the `custom.constants` argument is currently ignored in `ecr()`, it is not passed to the operators.
Best,
Miguel

**Comment by jakobbossek** [comment]
Hi Miguel, thanks for the bug report.

**Comment by jakobbossek** [comment]
Actually this argument was accidentally transferred from ecr 1.x. Following the design principles of ecr 2.x we do not bloat the number of arguments and corresponding code of operators. However, if you need your operators to make use of custom constants you can accomplish that easily, e.g.
```r
myMutator = makeMutator(
  fun = function(ind, args = list()) {
    # do mutation stuff and access constants via args$... 
  }
)

CONSTANTS = list(a = 1, b = 2)
res = ecr::ecr(..., mutator = ecr::setup(myMutator, args = CONSTANTS), ...)
```
