### ISSUE TITLE
Difference between "Probability of mutation of each gene" and "Probability to apply mutation to a child"

### ISSUE THREAD

**Issue by kevinwolz** [jakobbossek/ecr2#93]
At first (probably because I am a dumb, EMOA novice), I was selecting a "mutation rate" and applying it to both:
- "Probability of mutation of each gene" (argument p of ecr::mutPolynomial)
- "Probability to apply mutation to a child" (argument p.mut of ecr::mutate)

In fact, these are not the same thing at all! The same exact can be said for the analagous arguments related to recombination probabilities. 

I'm not sure the best way to do this, but perhaps the documentation and vignette can do a better job of distinguishing between these two values. It's also probably a good idea to have a specific documentation page that defines "gene", "child", etc. so that it is completely clear.

**Comment by jakobbossek** [comment]
@thllwg Please make it more explicit in the documentation of `ecr::mutate` and `eco::generateOffspring` what `p.mut` actually is good for and refer to further parameters of the specific mutation operators. However, we will not cover the difference between gene, allele, child etc. in the package documentation.
