### ISSUE TITLE
Selecting p.mut and p.recomb when using replaceMuPlusLambda

### ISSUE THREAD

**Issue by kevinwolz** [jakobbossek/ecr2#94]
I will briefly explain my situation. Perhaps it is a common one, in which case I would recommend trying to add some additional documentation to guide users. 

I have:
```
MU = 200
LAMBA = MU
p.mut = 0.2, 
p.recomb = 0.7
n.objectives = 4
```
number of genes per individual: 21
mutator: `mutPolynomial`
recombinator: `recSBX`

I am using `replaceMuPlusLambda` with `selNondom` as my selection strategy to roughly mimic NSGA-II. 

My problem is that when I use `generateOffspring` to generate LAMBA new offspring, many of these offspring are actually identical to a member of the previous population (ie. no recombination or mutation occurred). This makes sense because both `p.mut` and `p.recomb` are less than 1, so there will likely always be some members of the population that sneak past both mutation and recombination. 

But if this is the case, then that means when I send these offspring to my fitness function, I will be sending a good number of individuals that I have already tested! This is not good because my fitness function is very computationally expensive. Consequently, I want to make sure that (1) I am evaluating MU new individuals with each generation and (2) this therefore allows `replaceMuPlusLambda` to actually compare 200*2 unique individuals and use `selNondom` to select 200 from among them. 

As of right now, `replaceMuPlusLambda` only gets to compare 200 + 160 (approximately) individuals since ~40 individuals from the offspring population are unchanged from the parent population.

**Is it bad to set either/both `p.mut` and `p.recomb `to 1? Is this a common practice?**

Of course, even if `p.mut` or `p.recomb` are 1, this doesn't mean that `p` of `mutPolynomial` or p of `recSBX` also need to be zero (see #93). I imagine it is much worse to set these equal to 1, right?

Are there other ways of ensuring that I evaluate MU distinct, new individuals with each generation?

**Comment by jakobbossek** [comment]
I will give a detailed answer later.
Since your objective function is very cost intensive you should definitely consider model-based optimization. Check out our package [mlrMBO](https://github.com/mlr-org/mlrMBO). It is very well documented and tailored for computationally expensive settings.

**Comment by jakobbossek** [comment]
Totally forgot about this thread 🙈 
Is this still relevant?
More precise answer: Imagine an EA with mutation only. Then `p.mut = 1` is reasonable. The same applies to recombination only. However, it is quite common to set `p.recomb = 1` and the probability of mutation much less in some branches of evolutionary computation. As so often in heuristic optimization it heavily depends on the problem at hand.

I will close now. Fell free to reopen if this is still relevant and requires discussion.
